// Firebase config
const firebaseConfig = {
  apiKey: "AIzaSyCbj3YJiKDLwoCfg1jmljd4ui9NTWgrrYY",
  authDomain: "jobai-c8a18.firebaseapp.com",
  projectId: "jobai-c8a18",
  storageBucket: "jobai-c8a18.firebasestorage.app",
  messagingSenderId: "96307987386",
  appId: "1:96307987386:web:8ed517fd1e7f051e8dd383",
  measurementId: "G-96Y3NH2PYC"
};

firebase.initializeApp(firebaseConfig);

const auth = firebase.auth();
const db = firebase.firestore();

let editingId = null;

// SIGNUP
function signup() {
  auth.createUserWithEmailAndPassword(
    document.getElementById("email").value,
    document.getElementById("password").value
  ).catch(error => alert(error.message));
}

// LOGIN
function login() {
  auth.signInWithEmailAndPassword(
    document.getElementById("email").value,
    document.getElementById("password").value
  ).catch(error => alert(error.message));
}

// LOGOUT
function logout() {
  auth.signOut();
}

// AUTH STATE
auth.onAuthStateChanged(user => {
  document.getElementById("auth").style.display = user ? "none" : "block";
  document.getElementById("app").style.display = user ? "block" : "none";

  if (user) {
    myResumes();
  }
});

// GENERATE RESUME
function generate() {

  const name = document.getElementById("name").value;
  const job = document.getElementById("job").value;
  const skills = document.getElementById("skills").value;

  document.getElementById("resume").innerHTML = `
<div class="resume">
<h2>${name}</h2>
<h3>${job}</h3>
<hr>

<h4>Professional Summary</h4>
<p>
Motivated professional with experience in ${job}.
Skilled in ${skills}.
</p>

<h4>Skills</h4>
<p>${skills}</p>

<h4>Generated by JobAI</h4>
<p>🤖 AI Resume Builder</p>
</div>
`;

  const user = auth.currentUser;

  if (!user) return;

  if (editingId) {

    db.collection("resumes").doc(editingId).update({
      name,
      job,
      skills
    }).then(() => {
      editingId = null;
      myResumes();
    });

  } else {

    db.collection("resumes").add({
      userId: user.uid,
      name,
      job,
      skills,
      createdAt: new Date()
    }).then(() => {
      myResumes();
    });

  }

}

// SHOW RESUMES
function myResumes() {

  const user = auth.currentUser;

  if (!user) return;

  db.collection("resumes")
    .where("userId","==",user.uid)
    .get()
    .then(snapshot=>{

      let html="<h3>📂 My Resumes</h3>";

      snapshot.forEach(doc=>{

        const data=doc.data();

        html+=`
<div class="resume">

<h3>${data.name}</h3>

<p>${data.job}</p>

<p>${data.skills}</p>

<button onclick="editResume('${doc.id}','${data.name}','${data.job}','${data.skills}')">
✏️ Edit
</button>

<button onclick="deleteResume('${doc.id}')">
🗑️ Delete
</button>

</div>
`;

      });

      document.getElementById("myResumes").innerHTML=html;

    });

}

// EDIT
function editResume(id,name,job,skills){

editingId=id;

document.getElementById("name").value=name;
document.getElementById("job").value=job;
document.getElementById("skills").value=skills;

window.scrollTo(0,0);

}

// DELETE
function deleteResume(id){

if(!confirm("Delete this resume?")) return;

db.collection("resumes")
.doc(id)
.delete()
.then(()=>{
myResumes();
});

}

// DOWNLOAD PDF
function download(){

const element=document.getElementById("resume");

if(!element.innerHTML.trim()){
alert("Generate resume first.");
return;
}

html2pdf().from(element).save("JobAI-Resume.pdf");

}
